http:
  routers:
    frontend:
      rule: Host(`dev.localhost`)
      service: frontend

  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:5173
