services:
  traefik:
    image: traefik:v3.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - --api.insecure=true
      - --providers.docker=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/traefik.yaml
      - ./config/dynamic:/dynamic
